parameters:
    attribute.attribute_creator.class: Padam87\AttributeBundle\Listener\AttributeCreatorListener
    form.type.attributeCollection.class: Padam87\AttributeBundle\Form\Type\AttributeCollectionType

services:
    attribute.attribute_creator:
        class: %attribute.attribute_creator.class%
        tags:
            - { name: doctrine.event_listener, event: postLoad }

    form.type.attributeCollection:
        class: %form.type.attributeCollection.class%
        tags:
            - { name: form.type, alias: attributeCollection }
